app: # To use it run: docker-compose run app bash
  build: .
  dockerfile: Dockerfile # That's our Dockerfile path
  # env_file: .env # Set environment variables from an `.env` file, if needed
  environment:
    - MIX_ENV=dev # That's the environment mode, you know
  volumes:
    - .:/app # Here we're mounting our project's root directory inside the container
